server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: ${DB_USER}
      database: ${DB_PASSWORD}
      host: localhost
      port: 27017

wishlist:
  limit-products: ${WISHLIST_LIMIT_PRODUCTS:20}
springdoc:
  api-docs:
    path: /api-docs
